name: Linux
on: [push, pull_request]
env:
        BUILD_TYPE: Release

jobs:
        build:
                name: ${{ matrix.config.name }}
                runs-on: ${{ matrix.config.os }}
                strategy:
                        fail-fast: false
                        matrix:
                                config:
                                        - {
                                                name: "Ubuntu Latest GCC", artifact: "Linux.7z",
                                                os: ubuntu-latest,
                                                cc: "gcc", cxx: "g++"
                                          }
                steps:
                        - uses: actions/checkout@v1
                        - name: Print env
                          run: |
                                echo github.event.action: ${{ github.event.action }}
                                echo github.event_name: ${{ github.event_name }}
                        - name: Installing JDK for Linux
                          run: |
                                ./ci/install_dependencies.sh
                        - name: Build and run tests
                          shell: bash
                          run: |
                                ./ci/run_tests.sh
